import { JsonObject } from 'swagger-ui-express';
import { readSwaggerFile, normalizePath } from './functions';
import { SwaggerRouteStore } from '../routeStore';

/**
 * Organizes Swagger document paths into tags based on the segments of the path.
 * Usually defaults to the first segment after /api/ or just the first segment.
 */
export function organizeSwaggerTags(
  swaggerDocument: JsonObject,
  basePath: string = '/',
): JsonObject {
  const normalizedBase = basePath.replace(/^\/|\/$/g, '').toLowerCase();

  if (!swaggerDocument.paths) return swaggerDocument;

  swaggerDocument.tags = swaggerDocument.tags || [];
  type SwaggerTag = { name: string; description?: string };
  const tagsArray = swaggerDocument.tags as SwaggerTag[];
  const existingTagNames = new Set(tagsArray.map((t) => t.name));

  for (const pathKey of Object.keys(swaggerDocument.paths)) {
    // Try to find a tag name from the path (e.g., /api/users -> users)
    const segments = pathKey.split('/').filter(Boolean);
    let tagName = 'default';

    if (segments.length > 0) {
      // If segments[0] matches the normalized base path, use segments[1] as tag
      if (normalizedBase && segments[0]?.toLowerCase() === normalizedBase && segments.length > 1) {
        tagName = segments[1];
      } else {
        tagName = segments[0];
      }
    }

    if (!existingTagNames.has(tagName)) {
      const description = `${tagName?.charAt(0)?.toUpperCase() + tagName?.slice(1)} endpoints`;
      tagsArray.push({ name: tagName, description });
      existingTagNames.add(tagName);
    }

    const pathItem = swaggerDocument.paths[pathKey];
    for (const method of Object.keys(pathItem)) {
      const operation = pathItem[method];
      if (operation && typeof operation === 'object') {
        operation.tags = operation?.tags || [];
        if (!operation.tags.includes(tagName)) {
          operation.tags.push(tagName);
        }
      }
    }
  }
  return swaggerDocument;
}

export async function applyCustomRouteDescriptions(fullPath: string, basePath: string = '/') {
  const normalizedBase = basePath.startsWith('/') ? basePath : `/${basePath}`;

  // Read the generated swagger file.
  const swaggerDocument = await readSwaggerFile(fullPath);
  if (!swaggerDocument.paths) swaggerDocument.paths = {};

  // Filter the actual document paths by basePath to ensure isolation between multiple apps
  if (normalizedBase !== '/') {
    const filteredPaths: Record<string, any> = {};
    for (const [pathKey, pathValue] of Object.entries(swaggerDocument.paths || {})) {
      const normalizedPath = pathKey.startsWith('/') ? pathKey : `/${pathKey}`;
      if (normalizedPath.startsWith(normalizedBase)) {
        filteredPaths[pathKey] = pathValue;
      }
    }
    swaggerDocument.paths = filteredPaths;
  }

  // Filter custom routes from the global store that match this instance's base path
  const allCustomRoutes = SwaggerRouteStore.getRouteList();
  const customRoutes = allCustomRoutes.filter((route) => {
    const routePath = route.path.startsWith('/') ? route.path : `/${route.path}`;
    return normalizedBase === '/' || routePath.startsWith(normalizedBase);
  });

  // Create a lookup map of normalized paths from the auto-generated document.
  const autoGeneratedPaths: { [normalizedPath: string]: string } = {};
  for (const p of Object.keys(swaggerDocument.paths)) autoGeneratedPaths[normalizePath(p)] = p;

  //  Merge custom route data (body, description, parameters) into existing paths.
  for (const route of customRoutes) {
    const normalizedCustomPath = normalizePath(route.path);

    // Improved matching: try direct match, then try with/without trailing slash, then try suffixes (for basePaths)
    let originalPath = autoGeneratedPaths[normalizedCustomPath];
    if (!originalPath) {
      const possibleMatch = Object.keys(autoGeneratedPaths).find((p) => {
        // 1. Direct or slash variants
        if (
          p === normalizedCustomPath ||
          p === normalizedCustomPath + '/' ||
          normalizedCustomPath === p + '/'
        ) {
          return true;
        }

        // 2. Suffix match (handles prefixes like /api/v1/math/calculate matching just /calculate)
        if (
          p.endsWith(normalizedCustomPath) &&
          p.charAt(p.length - normalizedCustomPath.length - 1) === '/'
        ) {
          return true;
        }

        // 3. Param syntax conversion (:id -> {id}) and then match
        const openApiStyle = normalizedCustomPath.replace(/:([a-zA-Z0-9_]+)/g, '{$1}');
        if (p === openApiStyle || p.endsWith(openApiStyle)) return true;
        return false;
      });
      if (possibleMatch) originalPath = autoGeneratedPaths[possibleMatch];
    }

    if (originalPath) {
      // The path exists, so we can safely merge our custom data.
      const { method, description, body, parameters, responses } = route;
      const pathItem = swaggerDocument.paths[originalPath];

      if (pathItem[method]) {
        let requestBody = undefined;
        if (body && typeof body === 'object') {
          let schema: Record<string, unknown> = {};

          if ('$ref' in body) {
            // Handle Schema Reference
            schema = { $ref: body.$ref };
          } else {
            // Handle Inline Object
            const properties: Record<string, Record<string, unknown>> = {};
            for (const key in body) {
              if (key === 'default') continue;
              const val = (body as Record<string, unknown>)[key];
              const type = typeof val;
              properties[key] = {
                type: type === 'object' ? 'object' : type,
                example: val,
              };
            }
            const requiredNotDefault = Object.keys(body).filter((k) => k !== 'default');
            schema = { type: 'object', required: requiredNotDefault, properties };
          }

          requestBody = {
            content: {
              'application/json': {
                schema,
              },
            },
          };
        }
        // Merge description and requestBody
        pathItem[method].description = description?.text || pathItem[method]?.description || '';
        if (requestBody) pathItem[method].requestBody = requestBody;

        // Apply consumes/produces/tags if provided
        if (route.consumes) pathItem[method].consumes = route.consumes;
        if (route.produces) pathItem[method].produces = route.produces;

        const combinedTags = [...(pathItem[method]?.tags || [])];
        if (route.tag) combinedTags.push(route.tag);
        if (route.tags) combinedTags.push(...route.tags);

        if (combinedTags.length > 0) {
          pathItem[method].tags = Array.from(new Set(combinedTags));
        }

        // Merge parameters
        if (parameters && Array.isArray(parameters)) {
          if (!pathItem[method]?.parameters) {
            pathItem[method].parameters = [];
          }
          pathItem[method].parameters = [...pathItem[method].parameters, ...parameters];
        }

        // Merge responses
        if (responses && typeof responses === 'object') {
          pathItem[method].responses = { ...(pathItem[method]?.responses || {}), ...responses };
        }
      }
    }
  }

  return swaggerDocument;
}
