import { JsonObject } from 'swagger-ui-express';
import { readSwaggerFile, normalizePath } from './functions';
import { SwaggerRouteStore } from '../routeStore';

/**
 * Organizes Swagger document paths into tags based on the segments of the path.
 * Usually defaults to the first segment after /api/ or just the first segment.
 */
export function organizeSwaggerTags(swaggerDocument: JsonObject): JsonObject {
  if (!swaggerDocument.paths) return swaggerDocument;

  swaggerDocument.tags = swaggerDocument.tags || [];
  const existingTagNames = new Set((swaggerDocument.tags as any[]).map((t) => t.name));

  for (const pathKey of Object.keys(swaggerDocument.paths)) {
    // Try to find a tag name from the path (e.g., /api/users -> users)
    const segments = pathKey.split('/').filter(Boolean);
    let tagName = 'default';

    if (segments.length > 0) {
      // If starts with 'api', take the next one if available
      if (segments[0].toLowerCase() === 'api' && segments.length > 1) {
        tagName = segments[1];
      } else {
        tagName = segments[0];
      }
    }

    if (!existingTagNames.has(tagName)) {
      (swaggerDocument.tags as any[]).push({
        name: tagName,
        description: `${tagName.charAt(0).toUpperCase() + tagName.slice(1)} endpoints`,
      });
      existingTagNames.add(tagName);
    }

    const pathItem = swaggerDocument.paths[pathKey];
    for (const method of Object.keys(pathItem)) {
      const operation = pathItem[method];
      if (operation && typeof operation === 'object') {
        operation.tags = operation.tags || [];
        if (!operation.tags.includes(tagName)) {
          operation.tags.push(tagName);
        }
      }
    }
  }
  return swaggerDocument;
}

export async function applyCustomRouteDescriptions(fullPath: string) {
  // Read the generated swagger file.
  const swaggerDocument = await readSwaggerFile(fullPath);
  if (!swaggerDocument.paths) swaggerDocument.paths = {};

  // Create a lookup map of normalized paths from the auto-generated document.
  const autoGeneratedPaths: { [normalizedPath: string]: string } = {};
  for (const p of Object.keys(swaggerDocument.paths)) {
    autoGeneratedPaths[normalizePath(p)] = p;
  }
  //  Merge custom route data (body, description, parameters) into existing paths.
  const customRoutes = SwaggerRouteStore.getRouteList();

  for (const route of customRoutes) {
    const normalizedCustomPath = normalizePath(route.path);

    // Improved matching: try direct match, then try with/without trailing slash
    let originalPath = autoGeneratedPaths[normalizedCustomPath];
    if (!originalPath) {
      // Try to find a match by comparing normalized versions more flexibly
      const possibleMatch = Object.keys(autoGeneratedPaths).find(
        (p) =>
          p === normalizedCustomPath ||
          p === normalizedCustomPath + '/' ||
          normalizedCustomPath === p + '/',
      );
      if (possibleMatch) originalPath = autoGeneratedPaths[possibleMatch];
    }

    if (originalPath) {
      // The path exists, so we can safely merge our custom data.
      const { method, description, body, parameters } = route;
      const pathItem = swaggerDocument.paths[originalPath];

      if (pathItem[method]) {
        let requestBody = undefined;
        if (body && typeof body === 'object') {
          let schema: any = {};

          if ((body as any).$ref) {
            // Handle Schema Reference
            schema = { $ref: (body as any).$ref };
          } else {
            // Handle Inline Object
            const properties: Record<string, any> = {};
            for (const key in body) {
              if (key === 'default') continue;
              const val = (body as any)[key];
              const type = typeof val;
              properties[key] = {
                type: type === 'object' ? 'object' : type,
                example: val,
              };
            }
            schema = {
              type: 'object',
              required: Object.keys(body).filter((k) => k !== 'default'),
              properties,
            };
          }

          requestBody = {
            content: {
              'application/json': {
                schema,
              },
            },
          };
        }
        // Merge description and requestBody
        pathItem[method].description = description?.text || pathItem[method]?.description || '';
        if (requestBody) {
          pathItem[method].requestBody = requestBody;
        }

        // Apply consumes/produces/tags if provided
        if (route.consumes) pathItem[method].consumes = route.consumes;
        if (route.produces) pathItem[method].produces = route.produces;
        if (route.tags) {
          pathItem[method].tags = [...(pathItem[method].tags || []), ...route.tags];
        }

        // Merge parameters
        if (parameters && Array.isArray(parameters)) {
          pathItem[method].parameters = [...(pathItem[method].parameters || []), ...parameters];
        }

      } else {
        console.warn(
          `\x1b[33m[warn]: Method '${method.toUpperCase()}' not found for path '${originalPath}' in auto-generated docs. Custom data not applied.\x1b[0m`,
        );
      }
    } else {
      // The path from custom data does not exist in the auto-generated docs.
      console.warn(
        `\x1b[33m[warn]: Path '${route.path}' from custom swagger data not found in auto-generated routes. Please check your route definition.\x1b[0m`,
      );
    }
  }

  return swaggerDocument;
}
