import { JsonObject } from 'swagger-ui-express';
import { readSwaggerFile, normalizePath } from './functions';
import { SwaggerRouteStore } from '../routeStore';

/**
 * Organizes Swagger document paths into tags based on the segments of the path.
 */
export function organizeSwaggerTags(
  swaggerDocument: JsonObject,
  basePath: string = '/',
): JsonObject {
  const normalizedBase = basePath.replace(/^\/|\/$/g, '').toLowerCase();

  if (!swaggerDocument.paths) return swaggerDocument;

  swaggerDocument.tags = swaggerDocument.tags || [];
  type SwaggerTag = { name: string; description?: string };
  const tagsArray = swaggerDocument.tags as SwaggerTag[];
  const existingTagNames = new Set(tagsArray.map((t) => t.name));

  for (const pathKey of Object.keys(swaggerDocument.paths)) {
    const segments = pathKey.split('/').filter(Boolean);
    let tagName = 'default';

    if (segments.length > 0) {
      if (normalizedBase && segments[0]?.toLowerCase() === normalizedBase && segments.length > 1) {
        tagName = segments[1];
      } else {
        tagName = segments[0];
      }
    }

    if (!existingTagNames.has(tagName)) {
      const description = `${tagName?.charAt(0)?.toUpperCase() + tagName?.slice(1)} endpoints`;
      tagsArray.push({ name: tagName, description });
      existingTagNames.add(tagName);
    }

    const pathItem = swaggerDocument.paths[pathKey];
    for (const method of Object.keys(pathItem)) {
      const operation = pathItem[method];
      if (operation && typeof operation === 'object') {
        const op = operation as any;
        op.tags = op.tags || [];
        if (!op.tags.includes(tagName)) {
          op.tags.push(tagName);
        }
      }
    }
  }
  return swaggerDocument;
}

/**
 * Deduplicates parameters by name and 'in' location.
 */
function mergeParameters(existing: any[] = [], incoming: any[] = []) {
  const map = new Map<string, any>();

  // Add existing
  for (const p of existing) {
    const key = `${p.name}-${p.in}`;
    map.set(key, p);
  }

  // Overwrite with incoming
  for (const p of incoming) {
    const key = `${p.name}-${p.in}`;
    map.set(key, p);
  }

  return Array.from(map.values());
}

/**
 * Applies custom route descriptions and filters paths for multi-instance isolation.
 */
export async function applyCustomRouteDescriptions(
  fullPath: string,
  basePath: string = '/',
  doc?: JsonObject,
) {
  const normalizedBase = (basePath.startsWith('/') ? basePath : `/${basePath}`).toLowerCase();

  // Use provided document or read from disk.
  const swaggerDocument = doc || (await readSwaggerFile(fullPath));
  if (!swaggerDocument.paths) swaggerDocument.paths = {};

  // Ensure basic OpenAPI structure if missing
  if (!swaggerDocument.openapi && !swaggerDocument.swagger) {
    swaggerDocument.openapi = '3.0.3';
  }

  // Filter custom routes from the global store that match this instance's base path
  const allCustomRoutes = SwaggerRouteStore.getRouteList();
  const customRoutes = allCustomRoutes.filter((route) => {
    const routePath = route.path.startsWith('/')
      ? route.path.toLowerCase()
      : `/${route.path.toLowerCase()}`;
    return normalizedBase === '/' || routePath.startsWith(normalizedBase);
  });

  // In OpenAPI 3, basePath is handled via servers[].url.
  // We won't ruthlessly drop paths that don't match normalizedBase anymore.
  // We'll just ensure that servers has the correct base URL.
  if (normalizedBase !== '/') {
    if (!swaggerDocument.servers || swaggerDocument.servers.length === 0 || swaggerDocument.servers[0].url === '') {
      swaggerDocument.servers = [{ url: normalizedBase }];
    } else {
      swaggerDocument.servers.forEach((s: any) => {
        if (!s.url.endsWith(normalizedBase)) {
           s.url = s.url.replace(/\/$/, '') + normalizedBase;
        }
      });
    }
  }

  // Create a lookup map of normalized paths from the filtered document.
  const autoGeneratedPaths: { [normalizedPath: string]: string } = {};
  for (const p of Object.keys(swaggerDocument.paths)) {
    autoGeneratedPaths[normalizePath(p).toLowerCase()] = p;
  }

  // Merge custom route data
  for (const route of customRoutes) {
    const normalizedCustomPath = normalizePath(route.path).toLowerCase();

    // Use any to bypass persistent TS2322 compilation error
    let originalPath: any = autoGeneratedPaths[normalizedCustomPath];
    if (!originalPath) {
      // Try fuzzy matching (e.g. param syntax :id -> {id})
      const openApiStyle = normalizedCustomPath.replace(/:([a-zA-Z0-9_]+)/g, '{$1}');
      originalPath =
        autoGeneratedPaths[openApiStyle] ||
        Object.keys(autoGeneratedPaths).find(
          (p) => p.endsWith(openApiStyle) || openApiStyle.endsWith(p),
        );
    }

    // If path still doesn't exist, we CREATE it
    if (!originalPath) {
      originalPath = route.path.startsWith('/') ? route.path : `/${route.path}`;
      if (!swaggerDocument.paths[originalPath]) {
        swaggerDocument.paths[originalPath] = {};
      }
    }

    if (originalPath) {
      const { method, description, body, parameters, responses } = route;
      const pathItem = swaggerDocument.paths[originalPath];

      // Ensure the method object exists
      if (!pathItem[method]) {
        pathItem[method] = {
          responses: responses || { 200: { description: 'OK' } },
        };
      }

      const op = pathItem[method];
      let requestBody = undefined;
      if (body && typeof body === 'object') {
        let schema: Record<string, unknown> = {};
        if ('$ref' in body) {
          schema = { $ref: body.$ref };
        } else if ('type' in body && body.type === 'object') {
          schema = body; // Direct schema
        } else {
          const properties: Record<string, Record<string, unknown>> = {};
          for (const key in body) {
            if (key === 'default') continue;
            const val = (body as Record<string, unknown>)[key];
            const type = typeof val;
            properties[key] = { type: type === 'object' ? 'object' : type, example: val };
          }
          const requiredNotDefault = Object.keys(body).filter((k) => k !== 'default');
          schema = { type: 'object', required: requiredNotDefault, properties };
        }
        requestBody = { content: { 'application/json': { schema } } };
      }

      op.description = (description?.text || op.description || '') as string;
      if (description?.summary) op.summary = description.summary;
      if (requestBody) op.requestBody = requestBody;

      if (route.consumes) op.consumes = route.consumes;
      if (route.produces) op.produces = route.produces;

      const combinedTags = [...(op.tags || [])];
      if (route.tag) combinedTags.push(route.tag);
      if (route.tags) combinedTags.push(...route.tags);
      if (combinedTags.length > 0) {
        op.tags = Array.from(new Set(combinedTags));
      }

      // Fix for duplicated parameters: deduplicate by name and in location
      if (parameters && Array.isArray(parameters)) {
        op.parameters = mergeParameters(op.parameters, parameters);
      }

      if (responses && typeof responses === 'object') {
        op.responses = { ...(op.responses || {}), ...responses };
      }

      if (route.security) op.security = route.security;
    }
  }

  return swaggerDocument;
}
